version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - 'data:/var/lib/mysql'
    env_file: .env.dev

volumes:
  data:
    driver: local